################################################################################
# Copyright 2021 highstreet technologies GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '3.8'
services:
  sdnc-web:
    image: ${SDNC_WEB_IMAGE}
    container_name: sdnc-web
    ports: 
      - ${SDNC_WEB_PORT}:${SDNC_WEB_PORT}
    environment: 
      - ENABLE_OAUTH=true
      - WEBPROTOCOL=HTTPS
      - WEBPORT=${SDNC_WEB_PORT}
      - SDNRPROTOCOL=http
      - SDNRHOST=agent #sdnr
      - SDNRPORT=${SDNC_REST_PORT}
      - SSL_CERT_DIR=/opt/app/osaaf/local/certs
      - SSL_CERTIFICATE=cert.pem
      - SSL_CERTIFICATE_KEY=key.pem
      - TOPOURL=http://topology:3001
      - TILEURL=https://tile.openstreetmap.org
    volumes:
      - ./sdnc-web:/opt/app/osaaf/local/certs
    networks:
      dmz:
      smo:

  agent:
    image: ${SDNC_WEB_AGENT_IMAGE}
    container_name: odlux-onos-agent
    ports:
      - 8000:8000
    environment:
      ONOS_IP: ${SDNR_ONOS_IPv4}
    networks:
      dmz:
      smo:
      default:
        ipv4_address: ${SDNC_OAM_IPv4}
        ipv6_address: ${SDNC_OAM_IPv6}

  onos:
    image: alan0415/onos:2.2-u3 #alan0415/onos:2.2 #onosproject/onos:2.2.0
    container_name: onos
    ports:
      - 8181:8181
      - 8101:8101
      - 5005:5005
      - 830:830
      - 4334:4334
    environment:
      - AGENT_IP=${SDNC_OAM_IPv4}
      - AGENT_PORT=8000
      - dmaap_ip=172.19.0.6
    networks:
      dmz:
      smo:
      default:
        ipv4_address: ${SDNR_ONOS_IPv4}
        ipv6_address: 2001:db8:1:50::4

  ves-collector:
    image: ${VES_COLLECTOR_IMAGE}
    container_name: ves-collector
    environment:
      DMAAPHOST: onap-dmaap
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./ves-collector/collector.properties:/opt/app/VESCollector/etc/collector.properties
    networks:
      smo:
      default:
        ipv6_address: ${VES_COLLECTOR_OAM_IPv6}

networks:
  dmz:
    external: true
  smo:
    external: true
  default:
    driver: bridge
    name: oam
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.26.0.0/24
        gateway: 172.26.0.1
      - subnet:  ${NETWORK_SUBNET_OAM_IPv6}
        gateway: ${NETWORK_GATEWAY_OAM_IPv6}
